"""`fief config`: read the one-place config (nodes.toml + sops secrets).

- `export --node NAME` renders dotenv (node vars + decrypted secrets) for
  compose/systemd. Redirect to .env (gitignored).
- `get KEY` prints one decrypted secret value (for scripts; keep out of logs).
- `edit` opens config/secrets.yaml in sops (encrypts in place per .sops.yaml).
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
NODES_FILE = REPO_ROOT / "config" / "nodes.toml"
SECRETS_FILE = REPO_ROOT / "config" / "secrets.yaml"


def register(sub: argparse._SubParsersAction) -> None:
    cfg = sub.add_parser("config", help="one-place config (nodes.toml + secrets)")
    cfg_sub = cfg.add_subparsers(dest="config_cmd", required=True)
    export = cfg_sub.add_parser("export", help="render dotenv for a node")
    export.add_argument("--node", required=True)
    export.set_defaults(func=run)
    get = cfg_sub.add_parser("get", help="print one decrypted secret")
    get.add_argument("key")
    get.set_defaults(func=run)
    cfg_sub.add_parser("edit", help="edit secrets.yaml in sops").set_defaults(func=run)


def run(args: argparse.Namespace) -> int:
    if args.config_cmd == "export":
        return cmd_export(args.node)
    if args.config_cmd == "get":
        return cmd_get(args.key)
    return cmd_edit()


def sops_bin() -> str:
    found = shutil.which("sops")
    if not found:
        raise SystemExit(
            "sops binary not found (nix: nix-shell -p sops | apt: see "
            "https://github.com/mozilla/sops/releases)"
        )
    return found


def load_nodes(path: Path | None = None) -> dict:
    with open(path or NODES_FILE, "rb") as f:
        return tomllib.load(f)


def assert_encrypted(path: Path | None = None) -> None:
    """Refuse plaintext: the committed secrets file must carry a sops envelope."""
    target = path or SECRETS_FILE
    if not target.exists():
        raise SystemExit(
            f"{target} missing — copy config/secrets.example.yaml over it and "
            "encrypt with `sops config/secrets.yaml`"
        )
    text = target.read_text()
    if not re.search(r"(?m)^sops:", text) or "age:" not in text:
        raise SystemExit(
            f"{target} has no sops age envelope — refusing (encrypt it first)"
        )


def decrypt_secrets(path: Path | None = None) -> dict[str, str]:
    """Decrypt secrets.yaml via sops. Requires age key (SOPS_AGE_KEY/file)."""
    target = path or SECRETS_FILE
    if not target.exists():
        raise SystemExit(
            f"{target} missing — copy config/secrets.example.yaml and encrypt "
            "with `sops config/secrets.yaml`"
        )
    r = subprocess.run(
        [sops_bin(), "--decrypt", "--output-type", "json", str(target)],
        capture_output=True,
        text=True,
        check=False,
    )
    if r.returncode != 0:
        raise SystemExit(f"sops decrypt failed: {r.stderr.strip()[-300:]}")
    data = json.loads(r.stdout or "{}")
    return {k: v for k, v in data.items() if not k.startswith("sops")}


def _shell_quote(value: object) -> str:
    text = str(value)
    if not text or any(c in text for c in " \t\n\"'\\$`!#"):
        return "'" + text.replace("'", "'\"'\"'") + "'"
    return text


def render_dotenv(node: str, nodes: dict, secrets: dict[str, str]) -> str:
    try:
        cfg = nodes["nodes"][node]
    except KeyError:
        raise SystemExit(f"unknown node {node!r} (see config/nodes.toml)")
    lines = [f"# generated by `fief config export --node {node}` — DO NOT COMMIT"]
    for key, value in cfg.get("vars", {}).items():
        lines.append(f"{key}={_shell_quote(value)}")
    for key in cfg.get("secrets", []):
        if key not in secrets:
            raise SystemExit(f"secret {key!r} required by node {node!r} is missing")
        lines.append(f"{key}={_shell_quote(secrets[key])}")
    return "\n".join(lines) + "\n"


def cmd_export(node: str) -> int:
    sys.stdout.write(render_dotenv(node, load_nodes(), decrypt_secrets()))
    return 0


def cmd_get(key: str) -> int:
    secrets = decrypt_secrets()
    if key not in secrets:
        raise SystemExit(f"secret {key!r} not found")
    sys.stdout.write(str(secrets[key]))
    return 0


def cmd_edit() -> int:
    return subprocess.run([sops_bin(), str(SECRETS_FILE)], check=False).returncode
