from fief.config_cmd import _shell_quote, render_dotenv


def test_shell_quote():
    assert _shell_quote("simple") == "simple"
    assert _shell_quote("u:s3cret!") == "'u:s3cret!'"
    assert _shell_quote("") == "''"
    assert _shell_quote("a'b") == "'a'\"'\"'b'"


def test_render_dotenv():
    nodes = {
        "nodes": {
            "pi": {
                "vars": {"TAIL_HOSTNAME": "fief-pi"},
                "secrets": ["CHISEL_AUTH"],
            }
        }
    }
    text = render_dotenv("pi", nodes, {"CHISEL_AUTH": "u:s3cret!"})
    assert text == (
        "# generated by `fief config export --node pi` — DO NOT COMMIT\n"
        "TAIL_HOSTNAME=fief-pi\n"
        "CHISEL_AUTH='u:s3cret!'\n"
    )


def test_render_dotenv_unknown_node():
    import pytest

    with pytest.raises(SystemExit, match="unknown node"):
        render_dotenv("nope", {"nodes": {}}, {})


def test_render_dotenv_missing_secret():
    import pytest

    with pytest.raises(SystemExit, match="missing"):
        render_dotenv("pi", {"nodes": {"pi": {"secrets": ["X"]}}}, {})
