from fief.config_cmd import _shell_quote, render_dotenv, validate_node_role


def test_shell_quote():
    assert _shell_quote("simple") == "simple"
    assert _shell_quote("u:s3cret!") == "'u:s3cret!'"
    assert _shell_quote("") == "''"
    assert _shell_quote("a'b") == "'a'\"'\"'b'"


def test_render_dotenv():
    nodes = {
        "nodes": {
            "pi": {
                "role": "exit",
                "vars": {"FIEF_MESH_HOSTNAME": "fief-pi"},
                "secrets": ["CHISEL_AUTH"],
            }
        }
    }
    text = render_dotenv("pi", nodes, {"CHISEL_AUTH": "u:s3cret!"})
    assert text == (
        "# generated by `fief config export --node pi` — DO NOT COMMIT\n"
        "FIEF_MESH_HOSTNAME=fief-pi\n"
        "CHISEL_AUTH='u:s3cret!'\n"
    )


def test_render_dotenv_unknown_node():
    import pytest

    with pytest.raises(SystemExit, match="unknown node"):
        render_dotenv("nope", {"nodes": {}}, {})


def test_render_dotenv_missing_secret():
    import pytest

    with pytest.raises(SystemExit, match="missing"):
        render_dotenv(
            "pi",
            {"nodes": {"pi": {"role": "exit", "secrets": ["X"]}}},
            {},
        )


def test_validate_node_role_rejects():
    import pytest

    with pytest.raises(SystemExit, match="role"):
        validate_node_role("x", {})
    with pytest.raises(SystemExit, match="must not set"):
        validate_node_role(
            "pi",
            {"role": "exit", "vars": {"FIEF_MESH_SERVE": "1080"}, "secrets": []},
        )
    with pytest.raises(SystemExit, match="must not hold"):
        validate_node_role(
            "lap",
            {"role": "client", "vars": {}, "secrets": ["FIEF_MESH_KEY"]},
        )


def test_validate_node_role_accepts():
    # Empty placeholders and reserved site pass; hubs are unrestricted.
    validate_node_role(
        "pi",
        {
            "role": "exit",
            "vars": {"FIEF_MESH_ROUTES": ""},
            "secrets": ["FIEF_MESH_KEY"],
            "site": "friend-house",
        },
    )
    validate_node_role(
        "hf",
        {
            "role": "hub",
            "vars": {"FIEF_MESH_SERVE": "1080,1081"},
            "secrets": ["FIEF_MESH_KEY"],
        },
    )
