CHISEL_AUTH: ENC[AES256_GCM,data:eUjpGl84JDOMg2JNxNhc/nF+/vh9ZJwoPw4oo4ijoAi/LGQiyEC1t9Tkc3854mVoH7s=,iv:OrTDuGm1zy8pGZiiKf99JKPn/54u4ew7SDt1JpZJC+s=,tag:Wb4255NLSNxEA0/2vxwkIQ==,type:str]
SSH_PUBKEY: ENC[AES256_GCM,data:VCKt45OB5N1nAmNPgvD2+eyF2ozzZXn7QbJ75wQhqtg4OFOqmu0ekxCvUpVF7wFUg2ZdUygBXxUNFxMJAcVD/Vgn0xcwhK1/4wHLLh9+Gn37jCRjAYqpY/HzrYynJZDfiT4=,iv:BYfs7y74Qw/xXEsQuhoRfT8mvXSSqG4LxJP2DIk1aeo=,tag:B565iSnS/5pfN7mTbxs93w==,type:str]
FIEF_MESH_KEY: ENC[AES256_GCM,data:JfpS2JwHkWXsdxHQlIAPblL43Jcv9oFo7s7kKHJGbfjlOM1MCypfNE3XvpzZi6Ka5brPyO0h6Sdxs82rC4I=,iv:ulxZYwivwYey5k40LAPFW9HvjdUmjukhjBAEhlPReJc=,tag:395485okMxctYqTS8WaJGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TFBmYzJ4aVptMTFDZ3hM
            SzFwYUN2SXVkK0JQNndiQlZnU3Mxc0lSOWtRCnM1U3VHR2tLRDlyODdjNmxHMGxh
            Z2xDcm8vSDVlemQyTjJzcXI2c0pKd3cKLS0tIGJMOUo4QndCVjhTSGt6YWZ3Q0NL
            eG9KME5XRzVpeWdXR1hHVDhJTUdWQUEKvTtdOPmXzGjLpB2TkUNPnxbwJaKlQoja
            bFXe09JkMM/I5P7Df56KAd92keVTl7ZQJ++LttuId+/+LTSmooBuhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tulycx7vphpxkk23g8lwzclp576ahgt2jnlm2txddueqcpmlt56sy40s8m
    lastmodified: "2026-10-05T20:43:28Z"
    mac: ENC[AES256_GCM,data:1FuIw1AOX4Qv5/cuCYtMHQPenL/HnpdZhK3/6PH6e4agWrIRCRi3Se9o5m6jaAklX2VapeeWPHkRghluAnIrtlBS4nEwRWhclqVYubii/qJ/wI8w09UrYwngUpzfYlZ/OrMFvfms5gNgpxNNN66WNFa20BCDZT05ToT5/GWeJ6U=,iv:GVL1EiAz/okkjJSgsFoEqPoriwtlOF1Wm9PNlT6Q0n8=,tag:iWNiHOcrAMzw2+rdYmjzpw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
