CHISEL_AUTH: ENC[AES256_GCM,data:jMF6kmpwLpq3CpYCZ5wW,iv:Awvm/KNR/RNnYdlc1uNDdBHSjUX/+8NsxLVUS+//iRQ=,tag:NcTc7Ppoe5mQJtrH4mmizA==,type:str]
SSH_PUBKEY: ENC[AES256_GCM,data:Ywg20CqDe+aMailoGIJBfOT5ibp0Q+XdU7b5MIOH4QFdJyLh66BCg4t0mS18IDM+whxvUGrugLYGs6zA62OPWrsWAkQ9/Gipm62Gu+QtzgfhXb0y20ysqk9iPjXL9eNsUYOCkDrKiw==,iv:HWgO+X+hkiITG1QTqJmdRBwBJL2yryhWPUPaIrM8Zz0=,tag:nh0mkzFBnKeha49NQQ/O3g==,type:str]
FIEF_MESH_KEY: ENC[AES256_GCM,data:+FN9W1pRL0cbKJNRjfN00IBe7IyR8Pw0RiBX6mHbqfSLgebx6UjmVwxF1fHeIOIEspJYTsCXyZeomYgeyg==,iv:n6QwVvOnzWCJguu6vlPmAuzOReZTJLP8eO9n1R4+2tc=,tag:Bmm4h/Du6qlTcRg3qJTf9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUzN1dnM4Y1RmczQ3WTZx
            bTZpTmJ6SUQrOXVqNzQyZDVPaVB6dkNDRFRZCnpkZEkzdGcyQzhDb2FjU1hORnJ0
            YWg5eE0yRW1RZ0lsSXdQMXFPc2pOajgKLS0tIHUwZFd1NW9ySEg5YmtHRlVhb0NC
            dVF4amV2ZlZKSUtCRXRLYStTSllpSEkKBgWR/Oc7/SSfnuosmfiVd2raBYT0tx6O
            w704J8n17/fnJ3JR9/cED6ks427AaUyEgY4DqZt4uhInwK7B8B3kPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l5z6hkqxdndw9tdgyrq0yqrxnx4vxvv8n6a9t474x0kz246ajy6qau4llj
    lastmodified: "2026-09-30T22:57:23Z"
    mac: ENC[AES256_GCM,data:NV4y2ATKhR/kluFtrqqfer5brT3uqBPIefGyHgg2LQPflFI6Cx6+BivXUiXeadAfphj1F9Y6R3WgH5XnddPjqWW17elKrV/romzaw2l9RNhOB2OgbpTMD0ESmrn7W0TeUsmYBeXHo67FYSjZKrmX2/nTbvkNEoT89lISFmeZ2rY=,iv:HoMNxTaH57zCyhD2gLMurbGA2qTuMuX2V8fyvVZStLg=,tag:LxacrP3GAegoyyqLSmeFFg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
